### ISSUE TITLE
前端：进一步改进

### ISSUE THREAD

**Issue by northword** [zotero-chinese/zotero-plugins#94]
https://github.com/zotero-chinese/zotero-plugins/pull/90#issuecomment-1987235807

- [ ] zotero-chinese/website#7
- [ ] 图表少了一个 zotero-chinese/website#6 
- [x] 响应式
- [x] 导航里菜单的深色模式有些问题 不过不影响使用
- [ ] ~~优化图表页的依赖，最好能让highcharts和数据的构建结果分开，这样依赖可以不用每天更新（长期）~~
- [x] 恢复原来的《废弃的插件》《付费的插件》页面
- [x] 标签支持 zotero-chinese/zotero-plugins#18 
- [ ] 彻底拆分获取数据和网站构建——目前来看不需要，不过这意味着GitHub pages上的无法使用（base），除非在netlify上也获取一遍插件（~~API滥用？~~）
- [ ] 从 charts.json 读取数据生成标签
